### ISSUE TITLE
Side views

### ISSUE THREAD

**Issue by maurbeck** [menehune23/microjoy#1]
Do you have any images of the sides of the assembled board?

**Comment by menehune23** [comment]
Hi maurbec, I don't currently have any side pictures but I can try to add some when I have time. Are you curious about a certain dimension?

Thanks for checking out the project!

Andrew

**Comment by maurbeck** [comment]
I was curious what the mounting looked like for the MicroView.

**Comment by menehune23** [comment]
With the exception of the height of the through-board headers, the MicroView is nearly flush with the board. I will try to put up a photo soon. The fact that the headers are through-board allows the MicroView pins to pass through the board slightly, giving as low of profile as possible.

Andrew

**Comment by menehune23** [comment]
Hi there,

Here are a couple quick photos that show the MicroView headers. Hope that helps!

Andrew

**Comment by maurbeck** [comment]
It doesn't seem as if the images came through to github by yoru email.

**Comment by menehune23** [comment]
My apologies. If you give me your email address, I can send them to you. I haven't had time yet to upload them.

Take care,

Andrew

**Comment by maurbeck** [comment]
Ok, thanks. aurbekk@gmail

**Comment by menehune23** [comment]
Here you are. Thanks for your interest :)

**Comment by maurbeck** [comment]
No problem. It seems like a neat project to try out. I've been looking all over OSH park for boards that actually have a BOM to give them a shot and yours is the most complete so far. I think I'll try replacing your charger with an 18650 charger board I use for my LiPos. 

Did you find the microview worked fine at lipo voltage as opposed to 5v? I'm curious about adding a 5v step up.

I think I found everything I need on Aliexpress. I'll put an other in for the board from OSH now.

**Comment by menehune23** [comment]
I don't believe I ever tried 5V but the MicroView documentation should say if it supports it. I had no problems running the current configuration outlined on my github page.

Good luck and let me know how it turns out! As a tip, you may get some extra joysticks. They were the most fickle to work with as they can become damaged easily during soldering.

Andrew

**Comment by maurbeck** [comment]
Ya, I got a set of five figuring I wanted to build at least two of these
(given minimum run of boards is 3 and I have 2 microviews).

5pcs 3D rocker analog joystick thumb stick for PSP1000/PSP 1000 original
console controller joypad gamepad repair replacement
http://s.aliexpress.com/7zURzium

I think the MV wants 5v but can be under clocked at 3.5v. I've successfully
ran at both but didn't know how operation worked long term.

Do you know of any other OSH park boards with as much documentation as
yours? Really I just want to build any random things but soldering kits are
expensive.

**Comment by menehune23** [comment]
No I don't really know of other OSH Park boards that are documented. There are just so many on there and they can be submitted by anyone. There probably are some, but sifting through them to find one is the difficult part.

Andrew
