### ISSUE TITLE
BasicIO Joystick 

### ISSUE THREAD

**Issue by maurbeck** [menehune23/microjoy#3]
Hi there, I got it built!!

Are you ever able to get x=2,y=2, or a x=-2,y=2 on the joystick?

I can't seem to hit the farthest point in the top right or left on two of the joysticks I've tried so far...

**Comment by menehune23** [comment]
Great to hear! I recall being able to get a joystick to traverse the circumference of the circle in the test program. I do however also recall having lots of trouble with the joysticks. I had to go through a few. Unfortunately I think the process of disassembling them to solder can make them less reliable (or they may just be unreliable from the start).

Perhaps you could try connecting one with jumpers prior to soldering, so you can make a before and after comparison.

Good luck. Would love to see some pics!

**Comment by maurbeck** [comment]
I can get all directions, it's just that only a few corners are missing the full extent of |2|. 

I had to make a few modifications.

1. Used super tall stacking headers because that's all I could get and I wanted to finish the build today. Doesn't make it too high, but it'll be a bit weird if I make a 3D case for it.
2. Didn't imagine the right angle headers would be an abnormal spacing, so I had a fun time soldering extra component leads and bending them all around to make them work.
3. Didn't have a Sparkfun charger because I have a load of 18650 chargers.

![img_20160817_203206](https://cloud.githubusercontent.com/assets/2982395/17759064/1d7a5840-64ba-11e6-9ecf-d31ac681b5cb.jpg)
![img_20160817_203220](https://cloud.githubusercontent.com/assets/2982395/17759063/1d79eca2-64ba-11e6-9e43-25f63aca4632.jpg)
![img_20160817_203231](https://cloud.githubusercontent.com/assets/2982395/17759062/1d7955ee-64ba-11e6-9661-b9876555c581.jpg)
![img_20160817_203242](https://cloud.githubusercontent.com/assets/2982395/17759061/1d793f1e-64ba-11e6-9b6e-cd42c067ef2e.jpg)

Few notes/questions -
I can't ever get a Microview to work with just an FTDI cable. I have to use an FT232H from Adafruit and use a capacitor on the reset line. Can I just ground DTR right when the IDE is about to upload to replicate this?

Good call on the foam! It is quite pokey. I haven't got my single sided foam in yet.

I figured out the construction of the joypads if you need help re-assembling. I was able to remove the stick from the clamps after it was attached to my MicroJoy and replace it with another one to test it out.

Going to put foam under the battery too so I don't pierce the LiPo and have it explode in my face.

Love the game and the BasicIO sketch

This was my first Open Source project from board and parts to final build. I'm very happy with it and I'm grateful for all of your great documentation.

**Comment by menehune23** [comment]
Looks great! You're correct about the right angle headers. If you look on my BOM you can find the one I used so that you don't have to bend anything.

Regarding the FTDI, you should be able to solder (or use jumpers) a header to the FTDI section on top. There is already a cap on the board on the reset line for that purpose. This allows programming without having to remove the MicroView. Otherwise you would remove the MicroView and would plug it into a MicroView USB Programmer (also on the BOM I believe).

**Comment by maurbeck** [comment]
Ya, I have a problem with not looking at the specs on headers, lol. 

I just have an FTDI cable with 5v+/-, TX/RX. No reset available on it.

I always hate to buy special configured things when I can make them myself, so out of dumb principle I wont buy a Microview programmer, ha ^_^

I can deal with it!

I'm considering what kind of add-on boards I want to create for this. For example, plugging in a few weather sensors or upgrading my mobile Lux Meter:
![lux meter](https://cloud.githubusercontent.com/assets/2982395/17759831/8634c2c0-64c0-11e6-946a-9c6c72d200cf.jpg)

**Comment by menehune23** [comment]
Can you show a pic of your FTDI cable pins? It should work out of the box with the FTDI breakout along the top of the MicroJoy board.

**Comment by maurbeck** [comment]
Here is my cable
